import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { nextAuthOptions } from "../lib/next-auth/route";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(nextAuthOptions);
  if (!session) {
    redirect("/signin");
  }
  return (
    <div>{children}</div>
  );
}
