import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import { NextAuthProvider } from "@/lib/next-auth/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <NextAuthProvider>
          <div className="mx-auto sm:w-5/6 sm:mt-20 sm:mb-20 max-sm:w-11/12 max-sm:mt-14 max-sm:mb-20">{children}</div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
